theme: jekyll-theme-cayman
ğŸ [Home](https://manuelsr26.github.io/) | ğŸ“§ [email](mailto:manuel.isr@outlook.com) | [About](https://manuelsr26.github.io/about) | [Resume](https://manuelsr26.github.io/cv) | Blog | ğŸŒ California, USA | [LinkedIn](https://www.linkedin.com/in/manuel-silva-ramirez/)
